on:
  - pull_request
  - push

name: backwards compatibility

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
